### ISSUE TITLE
Support wagtailmodeladmin

### ISSUE THREAD

**Issue by alexgleason** [alexgleason/wagtailfontawesome#1]
Not sure why it doesn't work since icons in the side menu are included in nearly the same way as in StreamField.

**Comment by timheap** [comment]
its because the `insert_editor_css` hook only adds CSS on a model editing screen - pages, snippets, etc. Custom icons for wagtailmodeladmin might work when you're on an edit screen.

I think Wagtail are thinking of adding some extra hooks that can add custom CSS across the whole admin, instead of just in the edit screens. I dont know if there is an issue or PR for this though.

**Comment by alexgleason** [comment]
Fixed with the release of Wagtail 1.4.
