### ISSUE TITLE
Reason for the class name, `icon icon-fa-*`

### ISSUE THREAD

**Issue by FlipperPA** [alexgleason/wagtailfontawesome#15]
In all of the FontAwesome examples, their source in CDNs, and most templates/themes that use FontAwesome, the class follows this naming scheme:

    <i class="fa fa-example"></i>

However, for WagtailFontAwesome, we use this naming scheme:

    <i class="icon icon-fa-example"></i>

Is there a reason for this (Wagtail requirement I'm unaware of?), or would it be a good idea to come into line with FontAwesome's standard? It'd be nice to be able to use the included CSS code site-wide and with other packages.

This would be a backwards-breaking change, so if we do make it, we'd want to fully document the change. Perhaps as a `1.1.0` release.

**Comment by alexgleason** [comment]
Wagtail's admin templates append the `icon` classname to all icons it generates. In addition, the admin CSS refers to the `icon` classname in several different contexts. For instance, when an icon is within a StreamField it must be large; when an icon is in the left sidebar it must be positioned to the left of the text. These things happen by virtue of the `icon` classname, so we cannot remove support of it without breaking the admin styles.

Something we *could* do is add back support for the `fa` selector (and `fa-whatever` classes) so that both will work. I'm not sure it's good practice though; front-end is making less and less sense to me these days, especially regarding how dependencies should be handled.

**Comment by FlipperPA** [comment]
Yeah, you and me both.

I've got a CSS expert at work that I can ping for some wisdom on Monday on the best way to handle this. He's the friend who helped me with the new "Congrats!" page for Django.
